[package]
name = "hs"
version = "0.1.0"
edition = "2021"
author = "erguotou525@gmail.com"
about = "A http server with best practice for morden web application"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.29", features = ["derive"] }
actix-web = "4"
actix-files = "0.6.2"
