#!/usr/bin/env bash
set -e

function get_bin_name() {
  os_name=$(uname -s)
  cpu_arch=$(uname -m)
  if [ $os_name == "Darwin" ]; then
    if [ $cpu_arch == "arm64" ]; then
      bin_name="aarch64-apple-darwin"
    else
      bin_name="x86_64-apple-darwin"
    fi
  elif [ "$(expr substr $os_name 1 5)" == "Linux" ]; then
    bin_name="x86_64-unknown-linux-gnu"
  elif [ "$(expr substr $os_name 1 5)" == "MINGW" ]; then
    bin_name="x86_64-pc-windows-gnu"
    is_mingw=true
  fi
}


function download_hs() {
  bin_url="https://hs.erguotou.me/release/${bin_name}/${bin_name}.zip"
  echo $bin_url

  curl -o ${bin_name}.zip $bin_url
  # 解压并重命名为hs
  unzip ${bin_name}.zip
  rm ${bin_name}.zip
  if [ !$is_mingw ]; then
    chmod +x hs
  fi
}

get_bin_name
download_hs