name: Update docker readme
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/docker-readme.yml
      - README.md

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: "erguotou/hs"
          short-description: "A simple, high-performance, and resource-friendly web server like nginx"