# .github/workflows/release.yml

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

name: Release

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
          - target: x86_64-unknown-linux-musl
          - target: x86_64-apple-darwin
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
      - name: Install windows compiler
        if: matrix.target == 'x86_64-pc-windows-gnu'
        run: rustup target add x86_64-pc-windows-gnu && sudo apt-get install mingw-w64 -y
      - name: Install linux compiler
        if: matrix.target == 'x86_64-unknown-linux-musl'
        run: rustup target add x86_64-unknown-linux-musl
      - name: Install macos compiler
        if: matrix.target == 'x86_64-apple-darwin'
        run: |
          curl -L https://github.com/roblabla/MacOSX-SDKs/releases/download/13.3/MacOSX13.3.sdk.tar.xz | tar xJ
          export SDKROOT=$(pwd)/MacOSX13.3.sdk/
          export PATH=$PATH:~/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin/
          export CARGO_TARGET_X86_64_APPLE_DARWIN_LINKER=rust-lld
          rustup target add x86_64-apple-darwin
      - name: Build
        run: cargo build --all --release --target ${{ matrix.target }}
      - name: Strip
        if: matrix.target != 'x86_64-pc-windows-gnu'
        run: strip target/${{ matrix.target }}/release/hs
      - name: Archive
        run: zip -rj target//${{ matrix.target }}/release/hs.zip target//${{ matrix.target }}/release/hs
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target//${{ matrix.target }}/release/hs.zip
          asset_name: ${{ matrix.target }}.zip
          overwrite: true
          tag: ${{ github.ref }}