# .github/workflows/release.yml

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

name: Release

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
          - target: x86_64-unknown-linux-gnu
          # - target: x86_64-apple-darwin
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: |
          sudo apt-get update && sudo apt-get upgrade -y
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
      - name: Add build target
        run: rustup target add ${{ matrix.target }}
      - name: Install windows compiler
        if: matrix.target == 'x86_64-pc-windows-gnu'
        run: sudo apt-get install mingw-w64 -y
      - name: Build
        run: cargo build --all --release --target ${{ matrix.target }}
      - name: Strip & archive
        if: matrix.target != 'x86_64-pc-windows-gnu'
        run: |
          strip target/${{ matrix.target }}/release/hs
          zip -rj target/${{ matrix.target }}/release/hs.zip target/${{ matrix.target }}/release/hs
      - name: Strip windows & archive
        if: matrix.target == 'x86_64-pc-windows-gnu'
        run: |
          strip target/${{ matrix.target }}/release/hs.exe
          zip -rj target/${{ matrix.target }}/release/hs.zip target/${{ matrix.target }}/release/hs.exe
      # - name: Archive
      #   run: zip -rj target/${{ matrix.target }}/release/hs.zip target/${{ matrix.target }}/release/hs
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/${{ matrix.target }}/release/hs.zip
          asset_name: ${{ matrix.target }}.zip
          overwrite: true
          tag: ${{ github.ref }}
      - name: R2 Upload
        uses: gemwalletcom/r2-upload@v1.0.0
        with:
          endpoint: https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com
          access_key_id: ${{ secrets.R2_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          bucket: ${{ secrets.R2_BUCKET }}
          file: target/${{ matrix.target }}/release/hs.zip
          destination: ./release/${{ matrix.target }}.zip
  release-mac:
    name: release x86_64-apple-darwin
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-apple-darwin
          - target: aarch64-apple-darwin
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
      - name: Add build target
        run: rustup target add ${{ matrix.target }}
      - name: Build
        run: cargo build --all --release --target ${{ matrix.target }}
      - name: Strip
        run: strip target/${{ matrix.target }}/release/hs
      - name: Archive
        run: zip -rj target/${{ matrix.target }}/release/hs.zip target/${{ matrix.target }}/release/hs
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/${{ matrix.target }}/release/hs.zip
          asset_name: ${{ matrix.target }}.zip
          overwrite: true
          tag: ${{ github.ref }}
      - name: R2 Upload
        uses: gemwalletcom/r2-upload@v1.0.0
        with:
          endpoint: https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com
          access_key_id: ${{ secrets.R2_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          bucket: ${{ secrets.R2_BUCKET }}
          file: target/${{ matrix.target }}/release/hs.zip
          destination: ./release/${{ matrix.target }}.zip