# .github/workflows/release.yml

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

name: Release

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
          - target: x86_64-unknown-linux-musl
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: |
          sudo apt-get update && sudo apt-get upgrade -y
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
      - name: Add build target
        run: rustup target add ${{ matrix.target }}
      - name: Install windows compiler
        if: matrix.target == 'x86_64-pc-windows-gnu'
        run: sudo apt-get install mingw-w64 -y
      - name: Build windows
        if: matrix.target == 'x86_64-pc-windows-gnu'
        run: cargo build --all --release --target ${{ matrix.target }}
      - name: Build linux
        if: matrix.target == 'x86_64-unknown-linux-musl'
        run: TARGET_CC=x86_64-linux-musl-gcc cargo build --all --release --target ${{ matrix.target }}
      - name: Strip & archive
        if: matrix.target != 'x86_64-pc-windows-gnu'
        run: |
          strip target/${{ matrix.target }}/release/hs
          mkdir release
          zip -rj release/hs.zip target/${{ matrix.target }}/release/hs
      - name: Strip windows & archive
        if: matrix.target == 'x86_64-pc-windows-gnu'
        run: |
          strip target/${{ matrix.target }}/release/hs.exe
          mkdir release
          zip -rj release/hs.zip target/${{ matrix.target }}/release/hs.exe
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: release/hs.zip
          asset_name: ${{ matrix.target }}.zip
          overwrite: true
          tag: ${{ github.ref }}
      - name: R2 Upload Action
        uses: ryand56/r2-upload-action@latest
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.R2_BUCKET }}
          source-dir: release
          destination-dir: ./release/${{ matrix.target }}
  release-mac:
    name: release x86_64-apple-darwin
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-apple-darwin
          - target: aarch64-apple-darwin
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
      - name: Add build target
        run: rustup target add ${{ matrix.target }}
      - name: Build
        run: cargo build --all --release --target ${{ matrix.target }}
      - name: Strip & archive
        run: |
          strip target/${{ matrix.target }}/release/hs
          mkdir release
          zip -rj release/hs.zip target/${{ matrix.target }}/release/hs
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: release/hs.zip
          asset_name: ${{ matrix.target }}.zip
          overwrite: true
          tag: ${{ github.ref }}
      - name: R2 Upload Action
        uses: ryand56/r2-upload-action@latest
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.R2_BUCKET }}
          source-dir: release
          destination-dir: ./release/${{ matrix.target }}