# .github/workflows/release.yml

on:
  push:
    tags:
      - 'v*'

name: Release

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
          - target: x86_64-unknown-linux-musl
            archive: tar.gz tar.xz tar.zst
          - target: x86_64-apple-darwin
            archive: zip
    steps:
      - uses: actions/checkout@v4
      - name: Output openssl version
        run: openssl version
      - name: Install Windows openssl
        if: matrix.target == 'x86_64-pc-windows-gnu'
        run: |
          pacman -Syu
          pacman -S openssl
      - name: Set up Homebrew
        if: matrix.target == 'x86_64-apple-darwin'
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Install Mac openssl
        if: matrix.target == 'x86_64-apple-darwin'
        run: 
          brew update && brew upgrade openssl
      - name: Install Linux openssl
        if: matrix.target == 'x86_64-unknown-linux-musl'
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MACOSX_SDK_VERSION: 10.15
        with:
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}